
export const journalPosts = [
  {
    id: 0,
    title: "",
    excerpt: "",
    date: "",
    readTime: "",
    tags: [],
    image: "",
  },
    // {
    //   id: 1,
    //   title: "Building Accessible React Components",
    //   excerpt: "A deep dive into creating React components that work for everyone, including users with disabilities.",
    //   date: "2024-01-15",
    //   readTime: "8 min read",
    //   tags: ["React", "Accessibility", "Frontend"],
    //   image: "/accessible-react-components-code-editor.jpg",
    // },
    // {
    //   id: 2,
    //   title: "The Future of Web Development",
    //   excerpt: "Exploring emerging trends and technologies that are shaping the future of web development.",
    //   date: "2024-01-08",
    //   readTime: "12 min read",
    //   tags: ["Web Development", "Trends", "Technology"],
    //   image: "/futuristic-web-development-technology.jpg",
    // },
    // {
    //   id: 3,
    //   title: "Optimizing Next.js Performance",
    //   excerpt: "Practical tips and techniques for improving the performance of your Next.js applications.",
    //   date: "2024-01-01",
    //   readTime: "10 min read",
    //   tags: ["Next.js", "Performance", "Optimization"],
    //   image: "/nextjs-performance-optimization-dashboard.jpg",
    // },
    // {
    //   id: 4,
    //   title: "Design Systems at Scale",
    //   excerpt: "How to build and maintain design systems that scale across large organizations.",
    //   date: "2023-12-20",
    //   readTime: "15 min read",
    //   tags: ["Design Systems", "UI/UX", "Scalability"],
    //   image: "/design-system-ui-kit.png",
    // },
    // {
    //   id: 5,
    //   title: "TypeScript Best Practices",
    //   excerpt: "Essential TypeScript patterns and practices for building robust, type-safe applications.",
    //   date: "2023-12-15",
    //   readTime: "9 min read",
    //   tags: ["TypeScript", "Best Practices", "Development"],
    //   image: "/typescript-code-editor.jpg",
    // },
    // {
    //   id: 6,
    //   title: "State Management in Modern React",
    //   excerpt: "Comparing different state management solutions and when to use each approach in React applications.",
    //   date: "2023-12-10",
    //   readTime: "11 min read",
    //   tags: ["React", "State Management", "Architecture"],
    //   image: "/react-state-management.png",
    // },
    // {
    //   id: 7,
    //   title: "CSS Grid vs Flexbox",
    //   excerpt: "Understanding when to use CSS Grid and when to use Flexbox for modern web layouts.",
    //   date: "2023-12-05",
    //   readTime: "7 min read",
    //   tags: ["CSS", "Layout", "Frontend"],
    //   image: "/css-grid-flexbox.png",
    // },
    // {
    //   id: 8,
    //   title: "API Design Principles",
    //   excerpt: "Key principles for designing RESTful APIs that are intuitive, scalable, and maintainable.",
    //   date: "2023-11-28",
    //   readTime: "13 min read",
    //   tags: ["API", "Backend", "Architecture"],
    //   image: "/api-design-documentation.jpg",
    // },
  ]